### ISSUE TITLE
function without a prototype cannot be used or declared in a checked scope

### ISSUE THREAD

**Issue by Arslan8** [checkedc/checkedc#475]
Hi,
I am trying to compile a function using checkedC, however, i keep getting the missing prototype error. 
```
/home/arslan/zephyrproject/zephyr/samples/hello_world/src/main.c:13:1: error: function without a prototype cannot be used or declared in a checked scope
static void getCommand();
^
/home/arslan/zephyrproject/zephyr/samples/hello_world/src/main.c:15:1: error: function without a prototype cannot be used or declared in a checked scope
static void getCommand() {
^
```
On some digging,  adding a void parameter to the function argument fixed the problem. I am wondering if the error message is accurate here, or am i missing something?

**Comment by dtarditi** [comment]
This is by design. A function without a prototype cannot be called in a type-safe manner. Adding the void parameter changes this from a function with a prototype to a function that takes no arguments.
